/*
Nigerian Universities API

An API to get Nigerian universities by name or abbreviation.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UniversityNameRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UniversityNameRequest{}

// UniversityNameRequest struct for UniversityNameRequest
type UniversityNameRequest struct {
	Name string `json:"name"`
}

type _UniversityNameRequest UniversityNameRequest

// NewUniversityNameRequest instantiates a new UniversityNameRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUniversityNameRequest(name string) *UniversityNameRequest {
	this := UniversityNameRequest{}
	this.Name = name
	return &this
}

// NewUniversityNameRequestWithDefaults instantiates a new UniversityNameRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUniversityNameRequestWithDefaults() *UniversityNameRequest {
	this := UniversityNameRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UniversityNameRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UniversityNameRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UniversityNameRequest) SetName(v string) {
	o.Name = v
}

func (o UniversityNameRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UniversityNameRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UniversityNameRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUniversityNameRequest := _UniversityNameRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUniversityNameRequest)

	if err != nil {
		return err
	}

	*o = UniversityNameRequest(varUniversityNameRequest)

	return err
}

type NullableUniversityNameRequest struct {
	value *UniversityNameRequest
	isSet bool
}

func (v NullableUniversityNameRequest) Get() *UniversityNameRequest {
	return v.value
}

func (v *NullableUniversityNameRequest) Set(val *UniversityNameRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUniversityNameRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUniversityNameRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUniversityNameRequest(val *UniversityNameRequest) *NullableUniversityNameRequest {
	return &NullableUniversityNameRequest{value: val, isSet: true}
}

func (v NullableUniversityNameRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUniversityNameRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


